name: "Build & Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - run: |
        nix build
        export PATH=$PWD/result/bin:$PATH
        devenv shell devenv-test-cli
        devenv-run-tests --only trafficserver examples
